export const CREATE_TABLES = {
  assets: `
    CREATE TABLE IF NOT EXISTS assets (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      status TEXT NOT NULL,
      company_code TEXT,
      owner TEXT NOT NULL,
      location TEXT NOT NULL,
      purchase_date TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  assetCategories: `
    CREATE TABLE IF NOT EXISTS asset_categories (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL UNIQUE,
      label_zh TEXT NOT NULL,
      label_en TEXT NOT NULL,
      description TEXT,
      color TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  companies: `
    CREATE TABLE IF NOT EXISTS companies (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      code TEXT NOT NULL UNIQUE,
      description TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  roles: `
    CREATE TABLE IF NOT EXISTS roles (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      scope TEXT NOT NULL DEFAULT ('system'),
      description TEXT,
      member_user_ids TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  operations: `
    CREATE TABLE IF NOT EXISTS asset_operations (
      id TEXT PRIMARY KEY,
      asset_id TEXT NOT NULL,
      type TEXT NOT NULL,
      description TEXT,
      actor TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT ('done'),
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE
    );
  `,
  approvalRequests: `
    CREATE TABLE IF NOT EXISTS asset_approval_requests (
      id TEXT PRIMARY KEY,
      asset_id TEXT,
      consumable_id TEXT,
      operation_id TEXT,
      consumable_operation_id TEXT,
      type TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT ('pending'),
      title TEXT NOT NULL,
      reason TEXT,
      applicant_id TEXT NOT NULL,
      applicant_name TEXT,
      approver_id TEXT,
      approver_name TEXT,
      result TEXT,
      external_todo_id TEXT,
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      completed_at TEXT,
      FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE SET NULL,
      FOREIGN KEY(consumable_id) REFERENCES consumables(id) ON DELETE SET NULL,
      FOREIGN KEY(operation_id) REFERENCES asset_operations(id) ON DELETE SET NULL,
      FOREIGN KEY(consumable_operation_id) REFERENCES consumable_operations(id) ON DELETE SET NULL
    );
  `,
  consumableInventoryTasks: `
    CREATE TABLE IF NOT EXISTS consumable_inventory_tasks (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      scope TEXT,
      filters TEXT,
      owner TEXT,
      status TEXT NOT NULL DEFAULT ('draft'),
      description TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  consumableInventoryEntries: `
    CREATE TABLE IF NOT EXISTS consumable_inventory_entries (
      id TEXT PRIMARY KEY,
      task_id TEXT NOT NULL,
      consumable_id TEXT NOT NULL,
      consumable_name TEXT NOT NULL,
      category TEXT,
      keeper TEXT,
      expected_quantity INTEGER NOT NULL DEFAULT 0,
      expected_reserved INTEGER NOT NULL DEFAULT 0,
      actual_quantity INTEGER,
      actual_reserved INTEGER,
      variance_quantity INTEGER,
      variance_reserved INTEGER,
      note TEXT,
      status TEXT NOT NULL DEFAULT ('pending'),
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY(task_id) REFERENCES consumable_inventory_tasks(id) ON DELETE CASCADE,
      FOREIGN KEY(consumable_id) REFERENCES consumables(id) ON DELETE CASCADE
    );
  `,
  consumableAlerts: `
    CREATE TABLE IF NOT EXISTS consumable_alerts (
      id TEXT PRIMARY KEY,
      consumable_id TEXT NOT NULL,
      consumable_name TEXT NOT NULL,
      keeper TEXT,
      level TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT ('open'),
      message TEXT,
      quantity INTEGER NOT NULL DEFAULT 0,
      reserved_quantity INTEGER NOT NULL DEFAULT 0,
      external_todo_id TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      resolved_at TEXT,
      FOREIGN KEY(consumable_id) REFERENCES consumables(id) ON DELETE CASCADE
    );
  `,
  actionConfigs: `
    CREATE TABLE IF NOT EXISTS asset_action_configs (
      id TEXT PRIMARY KEY,
      label_zh TEXT NOT NULL,
      label_en TEXT NOT NULL,
      requires_approval INTEGER NOT NULL DEFAULT 0,
      default_approver_type TEXT NOT NULL DEFAULT ('none'),
      default_approver_refs TEXT,
      allow_override INTEGER NOT NULL DEFAULT 1,
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  operationTemplates: `
    CREATE TABLE IF NOT EXISTS asset_operation_templates (
      id TEXT PRIMARY KEY,
      type TEXT NOT NULL UNIQUE,
      label_zh TEXT NOT NULL,
      label_en TEXT NOT NULL,
      description_zh TEXT,
      description_en TEXT,
      require_attachment INTEGER NOT NULL DEFAULT 0,
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  borrowRecords: `
    CREATE TABLE IF NOT EXISTS asset_borrow_records (
      id TEXT PRIMARY KEY,
      asset_id TEXT NOT NULL,
      borrow_operation_id TEXT NOT NULL UNIQUE,
      borrower TEXT,
      borrower_token TEXT,
      server_origin TEXT,
      planned_return_date TEXT,
      status TEXT NOT NULL DEFAULT ('active'),
      return_operation_id TEXT,
      return_operation_date TEXT,
      overdue_notified_at TEXT,
      external_todo_id TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY(asset_id) REFERENCES assets(id) ON DELETE CASCADE,
      FOREIGN KEY(borrow_operation_id) REFERENCES asset_operations(id) ON DELETE CASCADE,
      FOREIGN KEY(return_operation_id) REFERENCES asset_operations(id) ON DELETE SET NULL
    );
  `,
  systemSettings: `
    CREATE TABLE IF NOT EXISTS system_settings (
      key TEXT PRIMARY KEY,
      value TEXT,
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  reportViews: `
    CREATE TABLE IF NOT EXISTS report_views (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      data_source TEXT NOT NULL,
      fields TEXT NOT NULL,
      filters TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  inventoryTasks: `
    CREATE TABLE IF NOT EXISTS asset_inventory_tasks (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      scope TEXT,
      filters TEXT,
      owner TEXT,
      status TEXT NOT NULL,
      description TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  consumableCategories: `
    CREATE TABLE IF NOT EXISTS consumable_categories (
      id TEXT PRIMARY KEY,
      code TEXT NOT NULL UNIQUE,
      label_zh TEXT NOT NULL,
      label_en TEXT NOT NULL,
      description TEXT,
      unit TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `,
  consumables: `
    CREATE TABLE IF NOT EXISTS consumables (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      status TEXT NOT NULL,
      company_code TEXT,
      quantity INTEGER NOT NULL DEFAULT 0,
      reserved_quantity INTEGER NOT NULL DEFAULT 0,
      unit TEXT NOT NULL DEFAULT ('pcs'),
      keeper TEXT NOT NULL DEFAULT (''),
      location TEXT NOT NULL DEFAULT (''),
      safety_stock INTEGER NOT NULL DEFAULT 0,
      description TEXT,
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY(category) REFERENCES consumable_categories(code) ON DELETE SET NULL
    );
  `,
  consumableOperations: `
    CREATE TABLE IF NOT EXISTS consumable_operations (
      id TEXT PRIMARY KEY,
      consumable_id TEXT NOT NULL,
      type TEXT NOT NULL,
      description TEXT,
      actor TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT ('done'),
      quantity_delta INTEGER NOT NULL DEFAULT 0,
      reserved_delta INTEGER NOT NULL DEFAULT 0,
      metadata TEXT,
      created_at TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at TEXT NOT NULL DEFAULT (datetime('now')),
      FOREIGN KEY(consumable_id) REFERENCES consumables(id) ON DELETE CASCADE
    );
  `,
};

export const seedAssets = [
  {
    id: "AST-001",
    name: "MacBook Pro 16 英寸",
    category: "Laptop",
    status: "in-use",
    company_code: "NEBULA",
    owner: "王小明",
    location: "上海总部",
    purchaseDate: "2024-01-15",
  },
  {
    id: "AST-002",
    name: "Dell PowerEdge R760",
    category: "Server",
    status: "idle",
    company_code: "NEBULA",
    owner: "基础架构组",
    location: "上海机房",
    purchaseDate: "2023-11-03",
  },
  {
    id: "AST-003",
    name: "海康威视摄像头",
    category: "Security",
    status: "maintenance",
    company_code: "VOYAGER",
    owner: "行政部",
    location: "北京办公区",
    purchaseDate: "2022-09-20",
  },
];

export const seedAssetCategories = [
  {
    id: "CAT-LAPTOP",
    code: "Laptop",
    label_zh: "笔记本电脑",
    label_en: "Laptop",
    description: "常规办公与移动开发设备",
    color: "#2563eb",
  },
  {
    id: "CAT-SERVER",
    code: "Server",
    label_zh: "服务器",
    label_en: "Server",
    description: "机房或云数据中心服务器",
    color: "#7c3aed",
  },
  {
    id: "CAT-SECURITY",
    code: "Security",
    label_zh: "安防设备",
    label_en: "Security",
    description: "摄像头、门禁等安防设备",
    color: "#059669",
  },
  {
    id: "CAT-NETWORK",
    code: "Network",
    label_zh: "网络设备",
    label_en: "Network",
    description: "交换机、路由器等网络设备",
    color: "#0f172a",
  },
  {
    id: "CAT-OTHER",
    code: "Other",
    label_zh: "其他资产",
    label_en: "Other",
    description: "暂未分类的其它资产",
    color: "#6b7280",
  },
];

export const seedCompanies = [
  {
    id: "COMP-001",
    name: "星云集团",
    code: "NEBULA",
    description: "总部位于上海的集团公司",
  },
  {
    id: "COMP-002",
    name: "远航科技",
    code: "VOYAGER",
    description: "深圳研发中心",
  },
];

export const seedRoles = [
  {
    id: "ROLE-ADMIN",
    name: "超级管理员",
    scope: "system",
    description: "拥有全部资产与配置权限",
    member_user_ids: null,
  },
  {
    id: "ROLE-ASSET-MANAGER",
    name: "资产管理员",
    scope: "asset",
    description: "负责资产新增、入库与盘点",
    member_user_ids: null,
  },
];

export const seedOperations = [
  // AST-001 MacBook Pro 16 英寸的操作记录
  {
    id: "OP-001",
    asset_id: "AST-001",
    type: "purchase",
    description: "完成采购审批并录入系统",
    actor: "王小明",
    status: "done",
  },
  {
    id: "OP-002",
    asset_id: "AST-001",
    type: "inbound",
    description: "资产入库并贴上二维码标签",
    actor: "仓库管理员",
    status: "pending", // 与 APR-002 审批状态保持一致
  },
  // AST-002 Dell PowerEdge R760 的操作记录
  {
    id: "OP-003",
    asset_id: "AST-002",
    type: "purchase",
    description: "采购服务器用于扩展机房容量",
    actor: "基础架构组",
    status: "done",
  },
  {
    id: "OP-004",
    asset_id: "AST-002",
    type: "inbound",
    description: "服务器到货并完成上架",
    actor: "仓库管理员",
    status: "done",
  },
  {
    id: "OP-005",
    asset_id: "AST-002",
    type: "maintenance",
    description: "例行巡检，更新 BIOS 固件",
    actor: "基础架构组",
    status: "done",
  },
  // AST-003 海康威视摄像头的操作记录
  {
    id: "OP-006",
    asset_id: "AST-003",
    type: "purchase",
    description: "采购安防摄像头用于北京办公区",
    actor: "行政部",
    status: "done",
  },
  {
    id: "OP-007",
    asset_id: "AST-003",
    type: "inbound",
    description: "摄像头到货并完成安装",
    actor: "仓库管理员",
    status: "done",
  },
  {
    id: "OP-008",
    asset_id: "AST-003",
    type: "maintenance",
    description: "摄像头镜头模糊，送修中",
    actor: "行政部",
    status: "pending",
  },
];

export const seedApprovalRequests = [
  // AST-001 MacBook Pro 16 英寸的审批记录
  {
    id: "APR-001",
    asset_id: "AST-001",
    consumable_id: null,
    operation_id: "OP-001",
    consumable_operation_id: null,
    type: "purchase",
    status: "approved",
    title: "采购 MacBook Pro 16 英寸",
    reason: "新成员入职需要开发设备",
    applicant_id: "user-asset-001",
    applicant_name: "王小明",
    approver_id: "ROLE-ADMIN",
    approver_name: "超级管理员",
    result: "同意采购并已完成下单",
    external_todo_id: null,
    metadata: JSON.stringify({ amount: 18999, currency: "CNY" }),
    completed_at: "2024-01-10T10:00:00.000Z",
  },
  {
    id: "APR-002",
    asset_id: "AST-001",
    consumable_id: null,
    operation_id: "OP-002",
    consumable_operation_id: null,
    type: "inbound",
    status: "pending",
    title: "MacBook Pro 入库确认",
    reason: "资产到货，需要仓库确认入库信息",
    applicant_id: "user-warehouse-001",
    applicant_name: "仓库管理员",
    approver_id: "ROLE-ASSET-MANAGER",
    approver_name: "资产管理员",
    result: null,
    external_todo_id: null,
    metadata: JSON.stringify({ photosRequired: true }),
    completed_at: null,
  },
  // AST-002 Dell PowerEdge R760 的审批记录
  {
    id: "APR-003",
    asset_id: "AST-002",
    consumable_id: null,
    operation_id: "OP-003",
    consumable_operation_id: null,
    type: "purchase",
    status: "approved",
    title: "采购 Dell PowerEdge R760 服务器",
    reason: "机房扩容，需要新增服务器节点",
    applicant_id: "user-infra-001",
    applicant_name: "基础架构组",
    approver_id: "ROLE-ADMIN",
    approver_name: "超级管理员",
    result: "同意采购，已走财务流程",
    external_todo_id: null,
    metadata: JSON.stringify({ amount: 89000, currency: "CNY" }),
    completed_at: "2023-10-20T14:30:00.000Z",
  },
  {
    id: "APR-004",
    asset_id: "AST-002",
    consumable_id: null,
    operation_id: "OP-004",
    consumable_operation_id: null,
    type: "inbound",
    status: "approved",
    title: "Dell 服务器入库确认",
    reason: "服务器到货，需确认配置并上架",
    applicant_id: "user-warehouse-001",
    applicant_name: "仓库管理员",
    approver_id: "ROLE-ASSET-MANAGER",
    approver_name: "资产管理员",
    result: "已完成上架并录入资产系统",
    external_todo_id: null,
    metadata: JSON.stringify({ rack: "R-A03", position: "U12-U14" }),
    completed_at: "2023-11-03T09:00:00.000Z",
  },
  // AST-003 海康威视摄像头的审批记录
  {
    id: "APR-005",
    asset_id: "AST-003",
    consumable_id: null,
    operation_id: "OP-006",
    consumable_operation_id: null,
    type: "purchase",
    status: "approved",
    title: "采购海康威视安防摄像头",
    reason: "北京办公区安防升级",
    applicant_id: "user-admin-001",
    applicant_name: "行政部",
    approver_id: "ROLE-ADMIN",
    approver_name: "超级管理员",
    result: "批准采购",
    external_todo_id: null,
    metadata: JSON.stringify({ amount: 2999, currency: "CNY" }),
    completed_at: "2022-09-10T11:00:00.000Z",
  },
  {
    id: "APR-006",
    asset_id: "AST-003",
    consumable_id: null,
    operation_id: "OP-007",
    consumable_operation_id: null,
    type: "inbound",
    status: "approved",
    title: "摄像头入库与安装确认",
    reason: "摄像头到货，需完成安装调试",
    applicant_id: "user-warehouse-001",
    applicant_name: "仓库管理员",
    approver_id: "ROLE-ASSET-MANAGER",
    approver_name: "资产管理员",
    result: "已安装并接入监控系统",
    external_todo_id: null,
    metadata: JSON.stringify({ installLocation: "北京办公区入口" }),
    completed_at: "2022-09-20T16:00:00.000Z",
  },
  {
    id: "APR-007",
    asset_id: "AST-003",
    consumable_id: null,
    operation_id: "OP-008",
    consumable_operation_id: null,
    type: "maintenance",
    status: "pending",
    title: "摄像头维修申请",
    reason: "摄像头镜头模糊，影响监控效果",
    applicant_id: "user-admin-001",
    applicant_name: "行政部",
    approver_id: "ROLE-ASSET-MANAGER",
    approver_name: "资产管理员",
    result: null,
    external_todo_id: null,
    metadata: JSON.stringify({ issue: "镜头模糊", priority: "medium" }),
    completed_at: null,
  },
];

export const seedActionConfigs = [
  {
    id: "purchase",
    label_zh: "采购",
    label_en: "Purchase",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "inbound",
    label_zh: "入库",
    label_en: "Inbound",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "receive",
    label_zh: "领用",
    label_en: "Receive",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "borrow",
    label_zh: "借用",
    label_en: "Borrow",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "return",
    label_zh: "归还",
    label_en: "Return",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "maintenance",
    label_zh: "维护",
    label_en: "Maintenance",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "dispose",
    label_zh: "报废",
    label_en: "Dispose",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "outbound",
    label_zh: "出库",
    label_en: "Outbound",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "reserve",
    label_zh: "预留",
    label_en: "Reserve",
    requires_approval: 0,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "release",
    label_zh: "释放预留",
    label_en: "Release",
    requires_approval: 0,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "adjust",
    label_zh: "库存调整",
    label_en: "Adjust",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
  {
    id: "other",
    label_zh: "其他",
    label_en: "Other",
    requires_approval: 1,
    default_approver_type: "none",
    default_approver_refs: JSON.stringify([]),
    allow_override: 1,
    metadata: null,
  },
];

export const seedOperationTemplates = [
  {
    id: "tpl-purchase",
    type: "purchase",
    label_zh: "采购流程",
    label_en: "Purchase",
    description_zh: "记录采购申请、预算和供应商信息。",
    description_en: "Capture purchase requests, budget, and vendor details.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["budget", "vendor", "expectedDate"],
    }),
  },
  {
    id: "tpl-inbound",
    type: "inbound",
    label_zh: "入库流程",
    label_en: "Inbound",
    description_zh: "入库确认可上传检验报告和收货照片。",
    description_en: "Upload inspection reports or delivery photos during inbound.",
    require_attachment: 1,
    metadata: JSON.stringify({
      fields: ["warehouse", "receiver", "photos"],
    }),
  },
  {
    id: "tpl-receive",
    type: "receive",
    label_zh: "领用流程",
    label_en: "Receive",
    description_zh: "记录领取人、用途和计划归还时间。",
    description_en: "Track recipient, usage note, and planned return date.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["receiver", "purpose", "returnPlan"],
    }),
  },
  {
    id: "tpl-borrow",
    type: "borrow",
    label_zh: "借用流程",
    label_en: "Borrow",
    description_zh: "借用需填写借用人、时长及押金凭证。",
    description_en: "Borrowing requires borrower details and deposit proof.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["borrower", "duration", "returnPlan", "depositAttachment"],
    }),
  },
  {
    id: "tpl-return",
    type: "return",
    label_zh: "归还流程",
    label_en: "Return",
    description_zh: "归还时可记录设备状态与异常说明。",
    description_en: "Record asset condition and exceptions when returning.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["condition", "notes"],
    }),
  },
  {
    id: "tpl-maintenance",
    type: "maintenance",
    label_zh: "维护流程",
    label_en: "Maintenance",
    description_zh: "维护记录需要维修商和费用信息。",
    description_en: "Capture vendor and cost information for maintenance.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["vendor", "cost", "report"],
    }),
  },
  {
    id: "tpl-dispose",
    type: "dispose",
    label_zh: "报废流程",
    label_en: "Disposal",
    description_zh: "报废需上传佐证资料并填写处理方式。",
    description_en: "Upload supporting documents and specify disposal method.",
    require_attachment: 1,
    metadata: JSON.stringify({
      fields: ["method", "evidence"],
    }),
  },
  {
    id: "tpl-outbound",
    type: "outbound",
    label_zh: "出库流程",
    label_en: "Outbound",
    description_zh: "记录出库目的地、接收人和运输信息。",
    description_en: "Record destination, recipient, and shipping details.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["destination", "recipient", "shippingMethod"],
    }),
  },
  {
    id: "tpl-reserve",
    type: "reserve",
    label_zh: "预留流程",
    label_en: "Reserve",
    description_zh: "预留资产/耗材供后续使用，记录预留原因和期限。",
    description_en: "Reserve assets/consumables for future use with reason and duration.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["reason", "duration", "reservedFor"],
    }),
  },
  {
    id: "tpl-release",
    type: "release",
    label_zh: "释放预留流程",
    label_en: "Release",
    description_zh: "释放已预留的资产/耗材，使其重新可用。",
    description_en: "Release reserved assets/consumables to make them available again.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["releaseReason", "notes"],
    }),
  },
  {
    id: "tpl-adjust",
    type: "adjust",
    label_zh: "库存调整流程",
    label_en: "Inventory Adjustment",
    description_zh: "调整库存数量，需说明调整原因（盘点差异、损耗等）。",
    description_en: "Adjust inventory quantities with reason (variance, shrinkage, etc.).",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["adjustmentType", "reason", "quantityDelta"],
    }),
  },
  {
    id: "tpl-other",
    type: "other",
    label_zh: "其它操作",
    label_en: "Other",
    description_zh: "用于记录其它资产操作，可自定义说明。",
    description_en: "Generic template for other asset operations.",
    require_attachment: 0,
    metadata: JSON.stringify({
      fields: ["notes"],
    }),
  },
];

export const DEFAULT_SYSTEM_SETTINGS = {
  consumableAlertsEnabled: "true",
  consumableAlertsPushEnabled: "true",
};

export const seedConsumableCategories = [
  {
    id: "CC-PRINT",
    code: "PrinterSupplies",
    label_zh: "打印耗材",
    label_en: "Printer Supplies",
    description: "墨盒、硒鼓等打印机耗材",
    unit: "pcs",
  },
  {
    id: "CC-OFFICE",
    code: "OfficeSupplies",
    label_zh: "办公用品",
    label_en: "Office Supplies",
    description: "常用办公耗材，如笔记本、便签等",
    unit: "pcs",
  },
];

export const seedConsumables = [
  {
    id: "CON-001",
    name: "黑色硒鼓 135A",
    category: "PrinterSupplies",
    status: "in-stock",
    company_code: "NEBULA",
    quantity: 24,
    reserved_quantity: 0,
    unit: "pcs",
    keeper: "行政部",
    location: "上海总部仓库",
    safety_stock: 10,
    description: "适配 HP LaserJet MFP 135w",
    metadata: null,
  },
  {
    id: "CON-002",
    name: "A4 复印纸 70g",
    category: "OfficeSupplies",
    status: "in-stock",
    company_code: "NEBULA",
    quantity: 80,
    reserved_quantity: 0,
    unit: "box",
    keeper: "行政部",
    location: "上海总部仓库",
    safety_stock: 30,
    description: "500 张/包，5 包/箱",
    metadata: null,
  },
];
