import fs from "fs";
import path from "path";
import { beforeEach, describe, expect, it } from "vitest";
import { resetDbForTesting } from "@/lib/db/client";
import { createAsset } from "@/lib/repositories/assets";
import {
  createAssetOperation,
  listOperationsForAsset,
} from "@/lib/repositories/asset-operations";
import {
  applyApprovalAction,
  createApprovalRequest,
  listApprovalRequests,
} from "@/lib/repositories/approvals";
import { getAssetById } from "@/lib/repositories/assets";

const TEST_DB_PATH = path.join(process.cwd(), "data", "test-approvals.db");

beforeEach(() => {
  process.env.NODE_ENV = "test";
  process.env.ASSET_HUB_DB_PATH = TEST_DB_PATH;
  if (fs.existsSync(TEST_DB_PATH)) {
    fs.rmSync(TEST_DB_PATH);
  }
  resetDbForTesting();
});

describe("Approval repository", () => {
  it("creates approval requests and lists them with filters", () => {
    const asset = createAsset({
      name: "Test Device",
      category: "Laptop",
      status: "idle",
      owner: "QA",
      location: "Lab",
      purchaseDate: "2024-03-01",
    });

    const operation = createAssetOperation(asset.id, {
      type: "purchase",
      actor: "QA",
      description: "申请采购",
      status: "pending",
    });

    createApprovalRequest({
      type: "purchase",
      title: "采购审批",
      reason: "入职需要设备",
      assetId: asset.id,
      operationId: operation.id,
      applicant: { id: "user-1", name: "QA" },
      approver: { id: "approver-1", name: "Leader" },
    });

    const result = listApprovalRequests({
      role: "my-requests",
      userId: "user-1",
    });

    expect(result.meta.total).toBe(1);
    expect(result.data[0].status).toBe("pending");
  });

  it("applies approval actions, updates asset state, and records metadata", () => {
    const asset = createAsset({
      name: "Camera",
      category: "Security",
      status: "in-use",
      owner: "Ops",
      location: "HQ",
      purchaseDate: "2023-12-01",
    });

    const operation = createAssetOperation(asset.id, {
      type: "inbound",
      actor: "Ops",
      description: "入库确认",
      status: "pending",
      metadata: {
        operationTemplate: {
          snapshot: {
            type: "inbound",
            labelZh: "入库确认",
            labelEn: "Inbound",
            requireAttachment: false,
            fields: [
              {
                key: "receiver",
                labelZh: "收货人",
                labelEn: "Receiver",
                widget: "text",
              },
            ],
          },
          values: {
            receiver: "Ops User",
          },
        },
      },
    });

    const approval = createApprovalRequest({
      type: "inbound",
      title: "入库审批",
      applicant: { id: "ops-user" },
      approver: { id: "manager-1", name: "Manager" },
      assetId: asset.id,
      operationId: operation.id,
    });

    const updated = applyApprovalAction(approval.id, {
      action: "approve",
      comment: "同意入库",
      actor: { id: "manager-1", name: "Manager" },
    });

    expect(updated.status).toBe("approved");
    expect(updated.result).toBe("同意入库");

    const updatedAsset = getAssetById(asset.id);
    expect(updatedAsset?.owner).toBe("Ops User");
    expect(updatedAsset?.status).toBe("idle");
  });

  it("creates a pending inbound operation after purchase approval passes", () => {
    const asset = createAsset({
      name: "Server",
      category: "Server",
      status: "idle",
      owner: "Infra",
      location: "DC",
      purchaseDate: "2024-01-01",
    });

    const approval = createApprovalRequest({
      type: "purchase",
      title: "采购审批",
      reason: "扩容需求",
      assetId: asset.id,
      applicant: { id: "infra-1", name: "Infra" },
      approver: { id: "cfo-1", name: "CFO" },
      metadata: {
        operationTemplate: {
          snapshot: {
            type: "purchase",
            labelZh: "采购申请",
            labelEn: "Purchase",
            requireAttachment: false,
            fields: [
              {
                key: "budget",
                labelZh: "预算",
                labelEn: "Budget",
                widget: "number",
              },
            ],
          },
          values: {
            budget: 120000,
          },
        },
      },
    });

    applyApprovalAction(approval.id, {
      action: "approve",
      actor: { id: "cfo-1", name: "CFO" },
    });

    const operations = listOperationsForAsset(asset.id);
    const pendingInbound = operations.find(
      (operation) =>
        operation.type === "inbound" &&
        operation.status === "pending" &&
        (operation.metadata as { autoGeneratedFromApprovalId?: unknown })
          ?.autoGeneratedFromApprovalId === approval.id,
    );

    expect(pendingInbound).toBeDefined();
    expect(
      (pendingInbound?.metadata as { operationTemplate?: unknown })
        ?.operationTemplate,
    ).toBeTruthy();
  });
});


