import type {
  OperationTemplateFieldValue,
  OperationTemplateId,
  OperationTemplateMetadata,
  OperationTemplateSnapshot,
  OperationTemplateSnapshotField,
  OperationTemplateValues,
} from "@/lib/types/operation-template";

const TEMPLATE_IDS: OperationTemplateId[] = [
  "purchase",
  "inbound",
  "receive",
  "borrow",
  "return",
  "maintenance",
  "dispose",
  "other",
];

const RESERVED_METADATA_KEYS = new Set([
  "operationTemplate",
  "templateSnapshot",
  "configSnapshot",
  "initiatedFrom",
  "autoGeneratedFromApprovalId",
  "autoGeneratedFromApprovalType",
  "sourceApprovalTitle",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function isStringArray(value: unknown): value is string[] {
  return (
    Array.isArray(value) && value.every((entry) => typeof entry === "string")
  );
}

function normalizeFieldValue(
  value: unknown,
): OperationTemplateFieldValue | undefined {
  if (
    typeof value === "string" ||
    typeof value === "number" ||
    value === null
  ) {
    return value;
  }
  if (isStringArray(value)) {
    return value;
  }
  return undefined;
}

function normalizeTemplateId(value: unknown): OperationTemplateId {
  if (
    typeof value === "string" &&
    TEMPLATE_IDS.includes(value as OperationTemplateId)
  ) {
    return value as OperationTemplateId;
  }
  return "other";
}

function parseSnapshotField(
  raw: unknown,
): OperationTemplateSnapshotField | null {
  if (!isRecord(raw) || typeof raw.key !== "string") {
    return null;
  }
  return {
    key: raw.key,
    labelZh: typeof raw.labelZh === "string" ? raw.labelZh : raw.key,
    labelEn: typeof raw.labelEn === "string" ? raw.labelEn : raw.key,
    widget:
      typeof raw.widget === "string" && raw.widget
        ? (raw.widget as OperationTemplateSnapshotField["widget"])
        : "text",
  };
}

function parseSnapshot(raw: unknown): OperationTemplateSnapshot | undefined {
  if (!isRecord(raw)) {
    return undefined;
  }

  const fieldsRaw = Array.isArray(raw.fields)
    ? raw.fields
        .map((field) => parseSnapshotField(field))
        .filter((field): field is OperationTemplateSnapshotField => !!field)
    : [];

  if (!fieldsRaw.length && typeof raw.type !== "string") {
    return undefined;
  }

  return {
    id: typeof raw.id === "string" ? raw.id : undefined,
    type: normalizeTemplateId(raw.type),
    labelZh:
      typeof raw.labelZh === "string"
        ? raw.labelZh
        : typeof raw.type === "string"
          ? raw.type
          : "operation",
    labelEn:
      typeof raw.labelEn === "string"
        ? raw.labelEn
        : typeof raw.type === "string"
          ? raw.type
          : "operation",
    requireAttachment:
      typeof raw.requireAttachment === "boolean"
        ? raw.requireAttachment
        : false,
    fields: fieldsRaw,
  };
}

function parseValues(raw: unknown): OperationTemplateValues | undefined {
  if (!isRecord(raw)) {
    return undefined;
  }
  const entries: OperationTemplateValues = {};
  Object.entries(raw).forEach(([key, value]) => {
    const normalized = normalizeFieldValue(value);
    if (normalized !== undefined) {
      entries[key] = normalized;
    }
  });

  return Object.keys(entries).length ? entries : undefined;
}

function collectLegacyValues(
  metadata: Record<string, unknown>,
): OperationTemplateValues | undefined {
  const entries: OperationTemplateValues = {};
  Object.entries(metadata).forEach(([key, value]) => {
    if (RESERVED_METADATA_KEYS.has(key)) {
      return;
    }
    const normalized = normalizeFieldValue(value);
    if (normalized !== undefined) {
      entries[key] = normalized;
    }
  });
  return Object.keys(entries).length ? entries : undefined;
}

function parseOperationTemplateMetadata(
  raw: unknown,
): OperationTemplateMetadata | null {
  if (!isRecord(raw)) {
    return null;
  }
  const snapshot = parseSnapshot(raw.snapshot);
  const values = parseValues(raw.values);
  if (!snapshot && !values) {
    return null;
  }
  return {
    snapshot,
    values,
  };
}

export function extractOperationTemplateMetadata(
  metadata?: Record<string, unknown> | null,
): OperationTemplateMetadata | null {
  if (!metadata) {
    return null;
  }

  const withWrapper = (metadata as { operationTemplate?: unknown })
    .operationTemplate;
  if (withWrapper) {
    const parsed = parseOperationTemplateMetadata(withWrapper);
    if (parsed) {
      return parsed;
    }
  }

  const snapshot = parseSnapshot(
    (metadata as { templateSnapshot?: unknown }).templateSnapshot,
  );
  const values = collectLegacyValues(metadata);
  if (!snapshot && !values) {
    return null;
  }
  return {
    snapshot,
    values,
  };
}

